server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8176
transformationDir: ${TRANSFORMATION_DIR}
ddsmMetamodelPath: ${DDSM_METAMODEL_PATH}
diceProfilePath: ${DICE_PROFILE_PATH}
secureUmlProfilePath: ${SECUREUML_PROFILE_PATH}
outMetamodelPath: ${OUT_METAMODEL_PATH}
